name: Fetch Data

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
    - run: ls -l 
      working-directory: ../
    - run: pwd
    - working-directory: ../
      run: python ./data.py
    