name: Fetch Data

on: push

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2.1.0
    - run: ls
    - run: pip install pandas
    - run: python data.py
    